dublin_codes = { 
    "Dublin 1" : ["Greene St", "Bolton St", "Gardiner Place", "Summerhill", "Abbey St", "Amiens St", "Capel St", "Dorset St","Henry St" ,"Mountjoy Sq" ,"Marlboro St", "North Wall",
    "O’Connell St","Cathal Brugha St","Marlborough St", "Parnell Sq", "Talbot St", "Parnell St", "Gardiner St", "Spencer Dock", "Custom House"],
    "Dublin 2" : ["Temple Bar", "Dawson St", "Hanover Quay", "Lower Baggot St", "Upper Baggot St", "Baggot St Upper", "Baggot St Lower", "College Green", "Fitzwilliam Square", "Harcourt St", "Kildare St",
    "Lord Edward St", "Merrion Square", "Mount St", "Nassau St", "Pearse St", "St. Stephen’s Green",
    "South Great Georges St", "Leeson Street Upper", "Leeson Street Lower", "Sir John Rogersons Quay", "Grand Canal", "Tara"],
    "Dublin 3" : ["Ballybough", "North Strand", "Ossory Road", "Clonliffe","Clontarf", "Dollymount", "East Wall", "Fairview", "Killester", "Marino", "Eastwall"],
    "Dublin 4" : ["Ballsbridge", "Donnybrook", "Irishtown", "Merrion", "Pembroke", "Ringsend", "Sandymount"],
    "Dublin 5" : ["Artane", "Coolock", "Harmonstown", "Kilbarrack", "Raheny", "Kilmore"],
    "Dublin 6" : ["Dartry", "Ranelagh", "Rathmines", "Rathgar", "Sandyford", "Milltown"],
    "Dublin 6W" : ["Terenure", "Harold's Cross", "Harolds Cross", "Templeogue", "Kimmage"],
    "Dublin 7" : ["Dominick St", "North Circular", "Arran Quay", "Navan Rd", "Navan Road", "Arbout Hill", "Cabra", "Phibsboro", "Phibsborough", "Four Courts", "Stoneybatter", "Smithfield"],
    "Dublin 8" : ["Ushers Quay", "South Circular", "Dolphin’s Barn", "Dolphins Barn", "Inchicore", "Island Bridge", "Islandbridge", "Kilmainham", "Merchants Quay", "Portobello", "South Circular Road", 
    "The Coombe", "Mount Brown", "Blackpitts", "Rialto", "Clanbrassil", "Christchurch", "Christ Church"],
    "Dublin 9" : ["Beaumont", "Drumcondra", "Ekm Mont", "Griffith Avenue", "Santry", "Whitehall", "Donnycarney", "Glasnevin", "Ballymun"],
    "Dublin 10" : ["Ballyfermot", "Cherry Orchard", "Cherryorchard"],
    "Dublin 11" : ["Meakstown", "Ballygal", "Cappagh", "Cremore", "Dubber", "Finglas", "Jamestown", "Kilshane", "Charlestown"],
    "Dublin 12" : ["Park West", "Bluebell", "Crumlin", "Drimnagh", "Walkinstown", "Greenhills", "Perrystown"],
    "Dublin 13" : ["Ayrfield", "Baily", "Baldoyle", "Bayside", "Donaghmede", "Sutton", "Howth", "Balgriffin", "Clongriffin"],
    "Dublin 14" : ["Churchtown", "Dundrum", "Goatstown", "Roebuck", "Windy Arbour", "Clonskeagh", "Rathfarnham", "Kilmacud"],
    "Dublin 15" : ["Hartstown", "Carpenterstown", "Porterstown", "Diswellstown", "Hansfield", "Blanchardstown", "Castleknock", "Castle Knock", "Clonee", "Clonsilla", "Corduff", "Mulhuddart", "Castaheany", "Tyrrelstown", "Ashtown", "Ongar", "Hollystown"],
    "Dublin 16" : ["Ballinteer", "Ballyboden", "Knocklyon", "Sandyford"],
    "Dublin 17" : ["Belcamp", "Balgrifin", "Clonshaugh", "Priorswood", "Darndale", "Riverside", "Clare Hall", "Clarehall"],
    "Dublin 18" : ["Cherrywood", "Rathmichael", "Cabinteely", "Carrickmines", "Foxrock", "Kilternan", "Sandyford", "Ticknock", "Ballyedmonduff", "Stepaside", "Leopardstown", "Shankill", "Loughlinstown", "Kiltiernan"],
    "Dublin 20" : ["Chapelizod", "Palmerstown"],
    "Dublin 22" : ["Bawnogue", "Clondalkin", "Neilstown"],
    "Dublin 24" : ["Springfield", "Firhouse", "Jobstown", "Kilnamanagh", "Oldbawn", "Tallaght", "Ballycullen", "Citywest", "City West", "Kiltipper", "Kingswood", "Belgard"],
    "Co. Dublin" : ["Lucan", "Rush", "Sandycove", "Blackrock", "Dún Laoghaire", "Dunlaoghaire", "Dun Laoghaire", "Swords", "Balbriggan", "Malahide", "Skerries", "Portmarnock", "Donabate", "Lusk", "Stillorgan", "Glenageary", "Killiney",
    "Adamstown", "Monkstown", "Newcastle", "Rathcoole", "Saggart", "Glasthule", "Dalkey", "Booterstown", "Balrothery", "Naul", "Sallynoggin", "Ballybrack", "Mount Merrion", "Oldtown", "Rolestown", "Bray", "Balrothery", "Brownsbarn",
    "Kinsealy", "Portrane", ]
}